version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo List all available files
      - ls -ll
      - echo Delete current model folder and fetch new model from s3
      - rm -rf model
      - aws s3 cp --recursive s3://${BUCKET_NAME}/final_model/ ./model
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .    
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - templates
    - application.py
    - docker-compose.yml
    - Dockerfile
    - requirements.txt
    - model